repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-toml
  - id: detect-private-key
  - id: check-yaml
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-added-large-files
  - id: mixed-line-ending

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
    - "--rcfile=pyproject.toml"

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types: [python]
