language: python
python:
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - python setup.py develop 
script:
  - py.test
notifications:
  email:
    on_success: never 
    on_failure: always 
