[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zetta_utils"
description = "Zetta AI Connectomics toolkit"
readme = "README.md"
authors = [{name = "Zetta AI team", email = "sergiy@zetta.ai"}]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
keywords = ["neuroscience connectomics EM"]
license = {text = "MIT"}
urls = {Homepage = "https://github.com/zettaai/zetta_utils"}
requires-python = ">= 3.8"
dependencies = [
    "attrs >= 21.3",
    "typeguard >= 2.13.3",
    "torch >= 1.11.0",
    "numpy >= 1.23.1",
    "connected-components-3d >= 3.10.0",
    "fastremap >= 1.12.2",
    "cloud-volume >= 8.7.0"
]
dynamic = ["version"]

[project.optional-dependencies]
viz = [
    "matplotlib >= 3.5.2",
    "ipywidgets >= 7.7.0",
    "opencv-python >= 4.5.5"
]
test = [
    "black == 21.9b0",
    "click ==8.0.1", # for black to work
    "pydocstyle == 6.1.1",
    "flake8 == 4.0.1",
    "mypy == 0.971",
    "pytest == 7.1.1",
    "pytest-cov == 3.0.0",
    "pytest-mock == 3.8.2",
    "isort == 5.10.1",
    "pylint == 2.13.9",
    "isort == 5.10.1",
    "pre-commit == 2.19.0",
]
all = [
    "zetta_utils[test]",
    "zetta_utils[viz]",
]

[tool.setuptools]
py-modules = []

[tool.black]
line-length = 99
target-version = ["py38","py39"]

[tool.pylint.format]
max-line-length = 99

[tool.pylint.basic]
good-names = '''a,b,c,d,df,do_POST,e,i,j,k,id,logger,n,on,ok,tz,x,y,z,r,ex,ey,cv,s'''

[tool.pylint.message_control]
disable = '''duplicate-code,C0330,cyclic-import,too-many-arguments,missing-docstring,too-few-public-methods'''
extension-pkg-allow-list = [
  "pymssql._mssql",
]

[tool.pylint.miscellaneous]
notes = '''FIXME,XXX'''

[tool.pylint.similarities]
min-similarity-lines = 4
ignore-comments = "yes"
ignore-docstrings = "yes"
ignore-imports = "yes"

[tool.pylint.main]
extension-pkg-whitelist="numpy,cc3d,fastremap"

[tool.pylint.options]
generated-members="torch.*"

[tool.pytest.ini_options]
addopts = "-ra --cov=zetta_utils --cov-report=term-missing --strict-markers --ignore=.eggs --tb=short --junitxml=test-results.xml --cov-report=html --cov-report=xml"
testpaths = ["tests"]
norecursedirs = ".env .git .venv build dist"
python_files = "test.py tests.py test_*.py *_test.py"

[tool.mypy]
    warn_unreachable = true
    warn_unused_ignores = true
    warn_redundant_casts = true
    warn_unused_configs = true
    #incremental = false
    #disallow_untyped_defs = true
    #check_untyped_defs = true
    #strict_equality = true
    implicit_reexport = true
    no_implicit_optional = true
