name: CI Pipeline

on:
  pull_request:
    type: [ opened, synchronize ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'false'
          submodules: 'recursive'
          ssh-key: ${{ secrets.git_ssh_key  }}
      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            docs_modified:
              - added|modified: "./docs/*"
            py_modified:
              - added|modified: "./zetta_utils/**/*.py"
      - name: Setup Python
        #if: ${{ steps.filter.outputs.docs_modified == 'true' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
          architecture: x64
          cache: 'pip'
      - name: Install Python dependencies
        #if: ${{ steps.filter.outputs.docs_modified == 'true' }}
        run: pip install -e '.[docs]'
      - name: Doctest
        run: cd ./docs; make doctest;
      - name: Build Docs
        run: make html
